language: node_js
node_js:
  - stable
cache: npm
install:
  - npm install  
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - npm run build
  - npm run test-with-coverage
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
  - bash <(curl -s https://codecov.io/bash) -f coverage/lcov.info
after_success:
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis CI"
  - sh .travis/generate_docs.sh
  - sh .travis/generate_changelog.sh
  - sh .travis/push.sh
  - npm pack
deploy:
- provider: releases
  api_key: $GH_TOKEN
  file_glob: true
  file: "{dicewerx}-*.tgz"
  skip_cleanup: true
  on:
    tags: true
- provider: npm
  email: "codemastermick@gmail.com"
  api_key: $NPM_TOKEN
  tag: latest
  skip_cleanup: true
  on:
    tags: true
