language: node_js
node_js:
  - stable
install:
  - npm install
  - npm install -g codecov
  - npm install -g istanbul
script:
  - npm test
  - istanbul cover node_modules/mocha/bin/_mocha
  - cat ./coverage/coverage.json | node_modules/codecov.io/bin/codecov.io.js
